AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Streaming Response with FastAPI on AWS Lambda

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 60

Resources:
  PrimaryCCCFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: PrimaryCCCStream
      PackageType: Image
      MemorySize: 512
      Environment:
        Variables:
          AWS_LWA_INVOKE_MODE: RESPONSE_STREAM
      FunctionUrlConfig:
        AuthType: NONE
        InvokeMode: RESPONSE_STREAM
        Cors:
          AllowMethods: "*"
          AllowHeaders: "*"
          AllowOrigins: "*"
      Tracing: Active
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: .
      DockerTag: v1
