name: Deploy to AWS Lambda
on: [push]

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read  

jobs:
  lambda_demo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1
      - name: Creating deployment zip
        run: |
          sudo apt install zip
          pip install -r requirements.txt -t .
          pip install snowflake-connector-python --platform manylinux2010_x86_64 --only-binary=:all: -t .
          zip -r lambda_zip.zip *
          ls .
      - name: Update Whitelist Lambda
        run: |
          aws lambda update-function-code --function-name getWhitelistArticulations --zip-file fileb://./lambda_zip.zip
